FilmLibrary.WebApp/Models/Genre.cs
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;

namespace FilmLibrary.WebApp.Models;

[DebuggerDisplay("Name: {Name}")]
public class Genre
{
    [Required(ErrorMessage = "El nombre es requerido.")]
    [MaxLength(255)]
    public string Name { get; set; } = "";
}

FilmLibrary.WebApp/Components/PageInformationViewComponent.cs
using FilmLibrary.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace FilmLibrary.WebApp.Components;

public class PageInformationViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(int currentPage, int totalPages)
    {
        return View(new PageInformationModel { CurrentPage = currentPage, TotalPages = totalPages });
    }
}

FilmLibrary.WebApp/Components/PageNavigationViewComponent.cs
using FilmLibrary.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace FilmLibrary.WebApp.Components;

public class PageNavigationViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(int currentPage, int pageSize, int totalPages, string? searchString)
    {
        var pageNavigationModel = new PageNavigationModel
        {
            CurrentPage = currentPage,
            PageSize = pageSize,
            TotalPages = totalPages,
            SearchString = searchString
        };
        return View(pageNavigationModel);
    }
}

FilmLibrary.WebApp/Components/RegistriesCountViewComponent.cs
using FilmLibrary.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace FilmLibrary.WebApp.Components;

public class RegistriesCountViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(int itemCount, int totalItems)
    {
        return View(new RegistriesCountModel { ItemCount = itemCount, TotalItems = totalItems });
    }
}

FilmLibrary.WebApp/Controllers/GenresController.cs
using FilmLibrary.Domain.Contracts.Repositories;
using FilmLibrary.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace FilmLibrary.WebApp.Controllers;

[Route("/genres")]
public class GenresController : Controller
{
    private readonly ILogger<GenresController> _logger;
    private readonly IGenreRepository _genreRepository;

    public GenresController(ILogger<GenresController> logger, IGenreRepository genreRepository)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _genreRepository = genreRepository ?? throw new ArgumentNullException(nameof(genreRepository));
    }

    public async Task<ActionResult> Index(string search, Pagination pagination)
    {
        if (string.IsNullOrEmpty(search))
        {
            var paginated = await _genreRepository.GetPaginatedAsync(pagination.Page, pagination.Count);
            return View(paginated);
        }
        else
        {
            var paginatedSearchResult = await _genreRepository.PaginatedSearchAsync(search, pagination.Page,
                pagination.Count);
            ViewBag.SearchString = search;
            return View(paginatedSearchResult);
        }
    }

    [HttpGet("add")]
    public ActionResult Add()
    {
        return View();
    }

    [HttpPost("add")]
    public async Task<ActionResult> Add(Genre genre)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }

        _genreRepository.Create(new Domain.Entities.Genre { Name = genre.Name });
        await _genreRepository.SaveAsync();

        return RedirectToAction("Index");
    }

    [HttpGet("details/{genreId}")]
    public async Task<ActionResult> Details(Guid genreId)
    {
        var genre = await _genreRepository.GetAsync(genreId);
        if (genre is null)
        {
            return RedirectToAction("Index");
        }

        return View(genre);
    }

    [HttpGet("edit/{genreId}")]
    public async Task<ActionResult> Edit(Guid genreId)
    {
        var genre = await _genreRepository.GetAsync(genreId);
        if (genre is null)
        {
            return RedirectToAction("Index");
        }

        return View(new Genre { Name = genre.Name });
    }

    [HttpPost("edit/{genreId}")]
    public async Task<ActionResult> Edit(Guid genreId, Genre genre)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }

        var currentGenre = await _genreRepository.GetAsync(genreId);
        if (currentGenre is not null)
        {
            currentGenre.Name = genre.Name;
            await _genreRepository.SaveAsync();
        }

        return RedirectToAction("Index");
    }

    [HttpGet("delete/{genreId}")]
    public async Task<ActionResult> Delete(Guid genreId)
    {
        var genre = await _genreRepository.GetAsync(genreId);
        if (genre is null)
        {
            return RedirectToAction("Index");
        }

        return View(genre);
    }

    [HttpPost("delete/{Id}")]
    public async Task<ActionResult> Delete(Domain.Entities.Genre genre)
    {
        var genreToDelete = await _genreRepository.GetAsync(genre.Id);
        if (genreToDelete is null)
        {
            return RedirectToAction("Index");
        }

        _genreRepository.Delete(genreToDelete);
        await _genreRepository.SaveAsync();

        return RedirectToAction("Index");
    }
}

FilmLibrary.WebApp/Views/Genres/Add.cshtml
@model Genre
@{ ViewData["Title"] = "Agregar género"; }

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Inicio</a></li>
        <li class="breadcrumb-item"><a asp-controller="Genres" asp-action="Index">Géneros</a></li>
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
</nav>

<h2>@ViewData["Title"]</h2>

<form method="post">
    @Html.AntiForgeryToken()

    <div class="mb-3">
        <label asp-for="Name" class="form-label">Nombre</label>
        <input type="text" asp-for="Name" class="form-control">
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>

    <div>
        <input type="submit" value="Agregar" class="btn btn-primary">
        <input type="reset" value="Restablecer" class="btn btn-secondary">
    </div>
</form>

<div class="mt-2">
    <a asp-action="Index" class="btn btn-info">Volver a la lista</a>
</div>

FilmLibrary.WebApp/Views/Genres/Create.cshtml
@model Genre
@{ ViewData["Title"] = "Crear género"; }

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Inicio</a></li>
        <li class="breadcrumb-item"><a asp-controller="Genres" asp-action="Index">Géneros</a></li>
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
</nav>

<h2>@ViewData["Title"]</h2>

<form method="post">
    @Html.AntiForgeryToken()

    <div class="mb-3">
        <label asp-for="Name" class="form-label">Nombre</label>
        <input type="text" asp-for="Name" class="form-control">
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>

    <div>
        <input type="submit" value="Crear" class="btn btn-primary">
        <input type="reset" value="Restablecer" class="btn btn-secondary">
    </div>
</form>

<div class="mt-2">
    <a asp-action="Index" class="btn btn-info">Volver a la lista</a>
</div>

FilmLibrary.WebApp/Views/Genres/Delete.cshtml
@model FilmLibrary.Domain.Entities.Genre
@{ ViewData["Title"] = "Eliminar género"; }

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Inicio</a></li>
        <li class="breadcrumb-item"><a asp-controller="Genres" asp-action="Index">Géneros</a></li>
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
</nav>

<h2>@ViewData["Title"]</h2>

<div class="alert alert-danger">¿Está seguro que desea eliminar este género?</div>

<div>
    <dl>
        <dt>Id</dt>
        <dd>@Model.Id</dd>
    </dl>
    <dl>
        <dt>Nombre</dt>
        <dd>@Model.Name</dd>
    </dl>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div>
        <input type="submit" class="btn btn-danger" value="Eliminar">
    </div>
}

<div class="mt-2">
    <a asp-action="Index" class="btn btn-info">Volver a la lista</a>
</div>

FilmLibrary.WebApp/Views/Genres/Details.cshtml
@model FilmLibrary.Domain.Entities.Genre
@{ ViewData["Title"] = "Detalle de género"; }

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Inicio</a></li>
        <li class="breadcrumb-item"><a asp-controller="Genres" asp-action="Index">Géneros</a></li>
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
</nav>

<h2>@ViewData["Title"]</h2>

<div>
    <dl>
        <dt>Id</dt>
        <dd>@Model.Id</dd>
    </dl>
    <dl>
        <dt>Nombre</dt>
        <dd>@Model.Name</dd>
    </dl>
</div>

<div class="mt-2">
    <a asp-action="Edit" asp-route-genreId="@Model.Id" class="btn btn-primary">Editar</a>
    <a asp-action="Delete" asp-route-genreId="@Model.Id" class="btn btn-danger">Eliminar</a>
    <a asp-action="Index" class="btn btn-info">Volver a la lista</a>
</div>

FilmLibrary.WebApp/Views/Genres/Edit.cshtml
@model Genre
@{ ViewData["Title"] = "Editar género"; }

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Inicio</a></li>
        <li class="breadcrumb-item"><a asp-controller="Genres" asp-action="Index">Géneros</a></li>
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
</nav>

<h2>@ViewData["Title"]</h2>

<form method="post">
    @Html.AntiForgeryToken()

    <div class="mb-3">
        <label asp-for="Name" class="form-label">Nombre</label>
        <input type="text" asp-for="Name" class="form-control">
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>

    <div>
        <input type="submit" class="btn btn-primary" value="Guardar">
        <input type="reset" class="btn btn-secondary" value="Restablecer">
    </div>
</form>

<div class="mt-2">
    <a asp-action="Index" class="btn btn-info">Volver a la lista</a>
</div>

FilmLibrary.WebApp/Views/Genres/Index.cshtml
@model FilmLibrary.Domain.Helper.PaginatedResult<FilmLibrary.Domain.Entities.Genre>
@{ ViewData["Title"] = "Géneros"; }

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Inicio</a></li>
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
</nav>

<h2>@ViewData["Title"]</h2>

<div class="d-flex flex-wrap gap-2 justify-content-between">
    <a asp-action="Add" class="btn btn-primary">Agregar género</a>
    <form class="d-flex" role="search">
        <input type="search" class="form-control me-2" name="search" placeholder="Búsqueda rápida" aria-label="Búsqueda"
               @{if (ViewBag.SearchString is not null) {<text>value="@ViewBag.SearchString"</text>}}>
        <input type="submit" value="Buscar" class="btn btn-success me-2">
        <a asp-action="Index" class="btn btn-secondary" asp-route-page="1">Borrar</a>
    </form>
</div>

<table class="table table-striped align-middle">
    <thead>
    <tr>
        <th>Nombre</th>
        <th>Acciones</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var genre in Model.Collection)
    {
        <tr>
            <td>
                <a asp-action="Details" asp-route-genreId="@genre.Id">@genre.Name</a>
            </td>
            <td>
                <div class="btn-group btn-group-sm" role="group" aria-label="Edition links">
                    <a asp-action="Edit" asp-route-genreId="@genre.Id" class="btn btn-outline-secondary">Editar</a>
                    <a asp-action="Delete" asp-route-genreId="@genre.Id" class="btn btn-outline-secondary">Eliminar</a>
                </div>
            </td>
        </tr>
    }
    </tbody>
    <tfoot>
    <tr>
        <td colspan="2">
            <div class="d-flex justify-content-between text-muted">
                @await Component.InvokeAsync("RegistriesCount",
                    new { itemCount = Model.ItemCount, totalItems = Model.TotalItems })
                @await Component.InvokeAsync("PageInformation",
                    new { currentPage = Model.CurrentPage, totalPages = Model.TotalPages })
            </div>
        </td>
    </tr>
    </tfoot>
</table>

@await Component.InvokeAsync("PageNavigation",
    new { currentPage = Model.CurrentPage, pageSize = Model.PageSize, totalPages = Model.TotalPages, searchString = ViewBag.SearchString })