FilmLibrary.WebApp/Models/Country.cs
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;

namespace FilmLibrary.WebApp.Models;

[DebuggerDisplay("Name: {Name}")]
public class Country
{
    [Required(ErrorMessage = "El nombre es requerido.")]
    [MaxLength(255)]
    public string Name { get; set; } = "";
}

FilmLibrary.WebApp/Components/PageInformationViewComponent.cs
using FilmLibrary.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace FilmLibrary.WebApp.Components;

public class PageInformationViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(int currentPage, int totalPages)
    {
        return View(new PageInformationModel { CurrentPage = currentPage, TotalPages = totalPages });
    }
}

FilmLibrary.WebApp/Components/PageNavigationViewComponent.cs
using FilmLibrary.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace FilmLibrary.WebApp.Components;

public class PageNavigationViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(int currentPage, int pageSize, int totalPages, string? searchString)
    {
        var pageNavigationModel = new PageNavigationModel
        {
            CurrentPage = currentPage,
            PageSize = pageSize,
            TotalPages = totalPages,
            SearchString = searchString
        };
        return View(pageNavigationModel);
    }
}

FilmLibrary.WebApp/Components/RegistriesCountViewComponent.cs
using FilmLibrary.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace FilmLibrary.WebApp.Components;

public class RegistriesCountViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(int itemCount, int totalItems)
    {
        return View(new RegistriesCountModel { ItemCount = itemCount, TotalItems = totalItems });
    }
}

FilmLibrary.WebApp/Controllers/CountriesController.cs
using FilmLibrary.Domain.Contracts.Repositories;
using FilmLibrary.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace FilmLibrary.WebApp.Controllers;

[Route("/countries")]
public class CountriesController : Controller
{
    private readonly ILogger<CountriesController> _logger;
    private readonly ICountryRepository _countryRepository;

    public CountriesController(ILogger<CountriesController> logger, ICountryRepository countryRepository)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _countryRepository = countryRepository ?? throw new ArgumentNullException(nameof(countryRepository));
    }

    public async Task<ActionResult> Index(string search, Pagination pagination)
    {
        if (string.IsNullOrEmpty(search))
        {
            var paginated = await _countryRepository.GetPaginatedAsync(pagination.Page, pagination.Count);
            return View(paginated);
        }
        else
        {
            var paginatedSearchResult = await _countryRepository.PaginatedSearchAsync(search, pagination.Page,
                pagination.Count);
            ViewBag.SearchString = search;
            return View(paginatedSearchResult);
        }
    }

    [HttpGet("add")]
    public ActionResult Add()
    {
        return View();
    }

    [HttpPost("add")]
    public async Task<ActionResult> Add(Country country)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }

        _countryRepository.Create(new Domain.Entities.Country { Name = country.Name });
        await _countryRepository.SaveAsync();

        return RedirectToAction("Index");
    }

    [HttpGet("details/{countryId}")]
    public async Task<ActionResult> Details(Guid countryId)
    {
        var country = await _countryRepository.GetAsync(countryId);
        if (country is null)
        {
            return RedirectToAction("Index");
        }

        return View(country);
    }

    [HttpGet("edit/{countryId}")]
    public async Task<ActionResult> Edit(Guid countryId)
    {
        var country = await _countryRepository.GetAsync(countryId);
        if (country is null)
        {
            return RedirectToAction("Index");
        }

        return View(new Country { Name = country.Name });
    }

    [HttpPost("edit/{countryId}")]
    public async Task<ActionResult> Edit(Guid countryId, Country country)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }

        var currentCountry = await _countryRepository.GetAsync(countryId);
        if (currentCountry is not null)
        {
            currentCountry.Name = country.Name;
            await _countryRepository.SaveAsync();
        }

        return RedirectToAction("Index");
    }

    [HttpGet("delete/{countryId}")]
    public async Task<ActionResult> Delete(Guid countryId)
    {
        var country = await _countryRepository.GetAsync(countryId);
        if (country is null)
        {
            return RedirectToAction("Index");
        }

        return View(country);
    }

    [HttpPost("delete/{Id}")]
    public async Task<ActionResult> Delete(Domain.Entities.Country country)
    {
        var countryToDelete = await _countryRepository.GetAsync(country.Id);
        if (countryToDelete is null)
        {
            return RedirectToAction("Index");
        }

        _countryRepository.Delete(countryToDelete);
        await _countryRepository.SaveAsync();

        return RedirectToAction("Index");
    }
}

FilmLibrary.WebApp/Views/Countries/Add.cshtml
@model Country
@{ ViewData["Title"] = "Agregar país"; }

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Inicio</a></li>
        <li class="breadcrumb-item"><a asp-controller="Countries" asp-action="Index">Países</a></li>
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
</nav>

<h2>@ViewData["Title"]</h2>

<form method="post">
    @Html.AntiForgeryToken()

    <div class="mb-3">
        <label asp-for="Name" class="form-label">Nombre</label>
        <input type="text" asp-for="Name" class="form-control">
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>

    <div>
        <input type="submit" value="Agregar" class="btn btn-primary">
        <input type="reset" value="Restablecer" class="btn btn-secondary">
    </div>
</form>

<div class="mt-2">
    <a asp-action="Index" class="btn btn-info">Volver a la lista</a>
</div>

FilmLibrary.WebApp/Views/Countries/Create.cshtml
@model Country
@{ ViewData["Title"] = "Crear país"; }

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Inicio</a></li>
        <li class="breadcrumb-item"><a asp-controller="Countries" asp-action="Index">Países</a></li>
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
</nav>

<h2>@ViewData["Title"]</h2>

<form method="post">
    @Html.AntiForgeryToken()

    <div class="mb-3">
        <label asp-for="Name" class="form-label">Nombre</label>
        <input type="text" asp-for="Name" class="form-control">
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>

    <div>
        <input type="submit" value="Crear" class="btn btn-primary">
        <input type="reset" value="Restablecer" class="btn btn-secondary">
    </div>
</form>

<div class="mt-2">
    <a asp-action="Index" class="btn btn-info">Volver a la lista</a>
</div>

FilmLibrary.WebApp/Views/Countries/Delete.cshtml
@model FilmLibrary.Domain.Entities.Country
@{ ViewData["Title"] = "Eliminar país"; }

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Inicio</a></li>
        <li class="breadcrumb-item"><a asp-controller="Countries" asp-action="Index">Países</a></li>
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
</nav>

<h2>@ViewData["Title"]</h2>

<div class="alert alert-danger">¿Está seguro que desea eliminar este país?</div>

<div>
    <dl>
        <dt>Id</dt>
        <dd>@Model.Id</dd>
    </dl>
    <dl>
        <dt>Nombre</dt>
        <dd>@Model.Name</dd>
    </dl>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div>
        <input type="submit" class="btn btn-danger" value="Eliminar">
    </div>
}

<div class="mt-2">
    <a asp-action="Index" class="btn btn-info">Volver a la lista</a>
</div>

FilmLibrary.WebApp/Views/Countries/Details.cshtml
@model FilmLibrary.Domain.Entities.Country
@{ ViewData["Title"] = "Detalle de país"; }

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Inicio</a></li>
        <li class="breadcrumb-item"><a asp-controller="Countries" asp-action="Index">Países</a></li>
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
</nav>

<h2>@ViewData["Title"]</h2>

<div>
    <dl>
        <dt>Id</dt>
        <dd>@Model.Id</dd>
    </dl>
    <dl>
        <dt>Nombre</dt>
        <dd>@Model.Name</dd>
    </dl>
</div>

<div class="mt-2">
    <a asp-action="Edit" asp-route-countryId="@Model.Id" class="btn btn-primary">Editar</a>
    <a asp-action="Delete" asp-route-countryId="@Model.Id" class="btn btn-danger">Eliminar</a>
    <a asp-action="Index" class="btn btn-info">Volver a la lista</a>
</div>

FilmLibrary.WebApp/Views/Countries/Edit.cshtml
@model Country
@{ ViewData["Title"] = "Editar país"; }

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Inicio</a></li>
        <li class="breadcrumb-item"><a asp-controller="Countries" asp-action="Index">Países</a></li>
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
</nav>

<h2>@ViewData["Title"]</h2>

<form method="post">
    @Html.AntiForgeryToken()

    <div class="mb-3">
        <label asp-for="Name" class="form-label">Nombre</label>
        <input type="text" asp-for="Name" class="form-control">
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>

    <div>
        <input type="submit" class="btn btn-primary" value="Guardar">
        <input type="reset" class="btn btn-secondary" value="Restablecer">
    </div>
</form>

<div class="mt-2">
    <a asp-action="Index" class="btn btn-info">Volver a la lista</a>
</div>

FilmLibrary.WebApp/Views/Countries/Index.cshtml
@model FilmLibrary.Domain.Helper.PaginatedResult<FilmLibrary.Domain.Entities.Country>
@{ ViewData["Title"] = "Países"; }

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Inicio</a></li>
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
</nav>

<h2>@ViewData["Title"]</h2>

<div class="d-flex flex-wrap gap-2 justify-content-between">
    <a asp-action="Add" class="btn btn-primary">Agregar país</a>
    <form class="d-flex" role="search">
        <input type="search" class="form-control me-2" name="search" placeholder="Búsqueda rápida" aria-label="Búsqueda"
               @{if (ViewBag.SearchString is not null) {<text>value="@ViewBag.SearchString"</text>}}>
        <input type="submit" value="Buscar" class="btn btn-success me-2">
        <a asp-action="Index" class="btn btn-secondary" asp-route-page="1">Borrar</a>
    </form>
</div>

<table class="table table-striped align-middle">
    <thead>
    <tr>
        <th>Nombre</th>
        <th>Acciones</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var country in Model.Collection)
    {
        <tr>
            <td>
                <a asp-action="Details" asp-route-countryId="@country.Id">@country.Name</a>
            </td>
            <td>
                <div class="btn-group btn-group-sm" role="group" aria-label="Edition links">
                    <a asp-action="Edit" asp-route-countryId="@country.Id" class="btn btn-outline-secondary">Editar</a>
                    <a asp-action="Delete" asp-route-countryId="@country.Id" class="btn btn-outline-secondary">Eliminar</a>
                </div>
            </td>
        </tr>
    }
    </tbody>
    <tfoot>
    <tr>
        <td colspan="2">
            <div class="d-flex justify-content-between text-muted">
                @await Component.InvokeAsync("RegistriesCount",
                    new { itemCount = Model.ItemCount, totalItems = Model.TotalItems })
                @await Component.InvokeAsync("PageInformation",
                    new { currentPage = Model.CurrentPage, totalPages = Model.TotalPages })
            </div>
        </td>
    </tr>
    </tfoot>
</table>

@await Component.InvokeAsync("PageNavigation",
    new { currentPage = Model.CurrentPage, pageSize = Model.PageSize, totalPages = Model.TotalPages, searchString = ViewBag.SearchString })