FilmLibrary.WebApp/Components/PageInformationViewComponent.cs
using FilmLibrary.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace FilmLibrary.WebApp.Components;

public class PageInformationViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(int currentPage, int totalPages)
    {
        return View(new PageInformationModel { CurrentPage = currentPage, TotalPages = totalPages });
    }
}

FilmLibrary.WebApp/Controllers/CountriesController.cs
using FilmLibrary.Domain.Contracts.Repositories;
using FilmLibrary.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace FilmLibrary.WebApp.Controllers;

[Route("/countries")]
public class CountriesController : Controller
{
    private readonly ILogger<CountriesController> _logger;
    private readonly ICountryRepository _countryRepository;

    public CountriesController(ILogger<CountriesController> logger, ICountryRepository countryRepository)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _countryRepository = countryRepository ?? throw new ArgumentNullException(nameof(countryRepository));
    }

    public async Task<ActionResult> Index(string search, Pagination pagination)
    {
        if (string.IsNullOrEmpty(search))
        {
            var paginated = await _countryRepository.GetPaginatedAsync(pagination.Page, pagination.Count);
            return View(paginated);
        }
        else
        {
            var paginatedSearchResult = await _countryRepository.PaginatedSearchAsync(search, pagination.Page,
                pagination.Count);
            ViewBag.SearchString = search;
            return View(paginatedSearchResult);
        }
    }

    [HttpGet("add")]
    public ActionResult Add()
    {
        return View();
    }

    [HttpPost("add")]
    public async Task<ActionResult> Add(Country country)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }

        _countryRepository.Create(new Domain.Entities.Country { Name = country.Name });
        await _countryRepository.SaveAsync();

        return RedirectToAction("Index");
    }

    [HttpGet("details/{countryId}")]
    public async Task<ActionResult> Details(Guid countryId)
    {
        var country = await _countryRepository.GetAsync(countryId);
        if (country is null)
        {
            return RedirectToAction("Index");
        }

        return View(country);
    }

    [HttpGet("edit/{countryId}")]
    public async Task<ActionResult> Edit(Guid countryId)
    {
        var country = await _countryRepository.GetAsync(countryId);
        if (country is null)
        {
            return RedirectToAction("Index");
        }

        return View(new Country { Name = country.Name });
    }

    [HttpPost("edit/{countryId}")]
    public async Task<ActionResult> Edit(Guid countryId, Country country)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }

        var currentCountry = await _countryRepository.GetAsync(countryId);
        if (currentCountry is not null)
        {
            currentCountry.Name = country.Name;
            await _countryRepository.SaveAsync();
        }

        return RedirectToAction("Index");
    }

    [HttpGet("delete/{countryId}")]
    public async Task<ActionResult> Delete(Guid countryId)
    {
        var country = await _countryRepository.GetAsync(countryId);
        if (country is null)
        {
            return RedirectToAction("Index");
        }

        return View(country);
    }

    [HttpPost("delete/{Id}")]
    public async Task<ActionResult> Delete(Domain.Entities.Country country)
    {
        var countryToDelete = await _countryRepository.GetAsync(country.Id);
        if (countryToDelete is null)
        {
            return RedirectToAction("Index");
        }

        _countryRepository.Delete(countryToDelete);
        await _countryRepository.SaveAsync();

        return RedirectToAction("Index");
    }
}

FilmLibrary.WebApp/Controllers/DirectorsController.cs
using FilmLibrary.Domain.Contracts.Repositories;
using FilmLibrary.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace FilmLibrary.WebApp.Controllers;

[Route("/directors")]
public class DirectorsController : Controller
{
    private readonly ILogger<DirectorsController> _logger;
    private readonly IDirectorRepository _directorRepository;

    public DirectorsController(ILogger<DirectorsController> logger, IDirectorRepository directorRepository)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _directorRepository = directorRepository ?? throw new ArgumentNullException(nameof(directorRepository));
    }

    public async Task<ActionResult> Index(string search, Pagination pagination)
    {
        if (string.IsNullOrEmpty(search))
        {
            var paginated = await _directorRepository.GetPaginatedAsync(pagination.Page, pagination.Count);
            return View(paginated);
        }
        else
        {
            var paginatedSearchResult = await _directorRepository.PaginatedSearchAsync(search, pagination.Page,
                pagination.Count);
            ViewBag.SearchString = search;
            return View(paginatedSearchResult);
        }
    }

    [HttpGet("add")]
    public ActionResult Add()
    {
        return View();
    }

    [HttpPost("add")]
    public async Task<ActionResult> Add(Director director)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }

        _directorRepository.Create(new Domain.Entities.Director { Name = director.Name });
        await _directorRepository.SaveAsync();

        return RedirectToAction("Index");
    }

    [HttpGet("details/{directorId}")]
    public async Task<ActionResult> Details(Guid directorId)
    {
        var director = await _directorRepository.GetAsync(directorId);
        if (director is null)
        {
            return RedirectToAction("Index");
        }

        return View(director);
    }

    [HttpGet("edit/{directorId}")]
    public async Task<ActionResult> Edit(Guid directorId)
    {
        var director = await _directorRepository.GetAsync(directorId);
        if (director is null)
        {
            return RedirectToAction("Index");
        }

        return View(new Director { Name = director.Name });
    }

    [HttpPost("edit/{directorId}")]
    public async Task<ActionResult> Edit(Guid directorId, Director director)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }

        var currentDirector = await _directorRepository.GetAsync(directorId);
        if (currentDirector is not null)
        {
            currentDirector.Name = director.Name;
            await _directorRepository.SaveAsync();
        }

        return RedirectToAction("Index");
    }

    [HttpGet("delete/{directorId}")]
    public async Task<ActionResult> Delete(Guid directorId)
    {
        var director = await _directorRepository.GetAsync(directorId);
        if (director is null)
        {
            return RedirectToAction("Index");
        }

        return View(director);
    }

    [HttpPost("delete/{Id}")]
    public async Task<ActionResult> Delete(Domain.Entities.Director director)
    {
        var directorToDelete = await _directorRepository.GetAsync(director.Id);
        if (directorToDelete is null)
        {
            return RedirectToAction("Index");
        }

        _directorRepository.Delete(directorToDelete);
        await _directorRepository.SaveAsync();

        return RedirectToAction("Index");
    }
}

FilmLibrary.WebApp/Controllers/FilmsController.cs
using FilmLibrary.Domain.Contracts.Repositories;
using FilmLibrary.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace FilmLibrary.WebApp.Controllers;

[Route("/films")]
public class FilmsController : Controller
{
    private readonly ILogger<FilmsController> _logger;
    private readonly IFilmRepository _filmRepository;
    private readonly IDirectorRepository _directorRepository;
    private readonly ICountryRepository _countryRepository;
    private readonly IGenreRepository _genreRepository;
    private readonly IRatingRepository _ratingRepository;

    public FilmsController(ILogger<FilmsController> logger, IFilmRepository filmRepository,
        IDirectorRepository directorRepository, ICountryRepository countryRepository,
        IGenreRepository genreRepository, IRatingRepository ratingRepository)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _filmRepository = filmRepository ?? throw new ArgumentNullException(nameof(filmRepository));
        _directorRepository = directorRepository ?? throw new ArgumentNullException(nameof(directorRepository));
        _countryRepository = countryRepository ?? throw new ArgumentNullException(nameof(countryRepository));
        _genreRepository = genreRepository ?? throw new ArgumentNullException(nameof(genreRepository));
        _ratingRepository = ratingRepository ?? throw new ArgumentNullException(nameof(ratingRepository));
    }

    public async Task<ActionResult> Index(string search, Pagination pagination)
    {
        if (string.IsNullOrEmpty(search))
        {
            var paginated = await _filmRepository.GetPaginatedAsync(pagination.Page, pagination.Count);
            return View(paginated);
        }
        else
        {
            var paginatedSearchResult = await _filmRepository.PaginatedSearchAsync(search, pagination.Page,
                pagination.Count);
            ViewBag.SearchString = search;
            return View(paginatedSearchResult);
        }
    }

    [HttpGet("add")]
    public async Task<ActionResult> Add()
    {
        var directors = await _directorRepository.GetAllAsync();
        var countries = await _countryRepository.GetAllAsync();
        var genres = await _genreRepository.GetAllAsync();

        if (directors.Count == 0 || countries.Count == 0 || genres.Count == 0)
        {
            ViewBag.Directors = directors.Count == 0;
            ViewBag.Countries = countries.Count == 0;
            ViewBag.Genres = genres.Count == 0;
            return View("MissingData");
        }

        ViewBag.Directors = directors;
        ViewBag.Countries = countries;
        ViewBag.Genres = genres;
        ViewBag.Ratings = await _ratingRepository.GetAllAsync();
        return View();
    }

    [HttpPost("add")]
    public async Task<ActionResult> Add(Film film)
    {
        if (!ModelState.IsValid)
        {
            ViewBag.Directors = await _directorRepository.GetAllAsync();
            ViewBag.Countries = await _countryRepository.GetAllAsync();
            ViewBag.Ratings = await _ratingRepository.GetAllAsync();
            ViewBag.Genres = await _genreRepository.GetAllAsync();
            return View(film);
        }

        var genres = await _genreRepository.GetMultipleAsync(film.GenreIds);

        _filmRepository.Create(new Domain.Entities.Film
        {
            Title = film.Title,
            Year = film.Year!.Value,
            DirectorId = film.DirectorId!.Value,
            Plot = film.Plot,
            RatingId = film.RatingId!.Value,
            ReleaseDate = film.ReleaseDate!.Value,
            CountryOfOriginId = film.CountryOfOriginId!.Value,
            Genres = genres
        });
        await _filmRepository.SaveAsync();

        return RedirectToAction("Index");
    }

    [HttpGet("details/{filmId}")]
    public async Task<ActionResult> Details(Guid filmId)
    {
        var film = await _filmRepository.GetAsync(filmId);
        if (film is null)
        {
            return RedirectToAction("Index");
        }

        return View(film);
    }

    [HttpGet("edit/{filmId}")]
    public async Task<ActionResult> Edit(Guid filmId)
    {
        var film = await _filmRepository.GetAsync(filmId);
        if (film is null)
        {
            return RedirectToAction("Index");
        }

        ViewBag.Directors = await _directorRepository.GetAllAsync();
        ViewBag.Countries = await _countryRepository.GetAllAsync();
        ViewBag.Ratings = await _ratingRepository.GetAllAsync();
        ViewBag.Genres = await _genreRepository.GetAllAsync();

        return View(new Film
        {
            Title = film.Title,
            Year = film.Year,
            DirectorId = film.DirectorId,
            Plot = film.Plot,
            RatingId = film.RatingId,
            ReleaseDate = film.ReleaseDate,
            CountryOfOriginId = film.CountryOfOriginId,
            GenreIds = film.Genres.Select(g => g.Id).ToList()
        });
    }

    [HttpPost("edit/{filmId}")]
    public async Task<ActionResult> Edit(Guid filmId, Film film)
    {
        if (!ModelState.IsValid)
        {
            ViewBag.Directors = await _directorRepository.GetAllAsync();
            ViewBag.Countries = await _countryRepository.GetAllAsync();
            ViewBag.Ratings = await _ratingRepository.GetAllAsync();
            ViewBag.Genres = await _genreRepository.GetAllAsync();
            return View(film);
        }

        var genres = await _genreRepository.GetMultipleAsync(film.GenreIds);
        var currentFilm = await _filmRepository.GetAsync(filmId);
        if (currentFilm is not null)
        {
            currentFilm.Title = film.Title;
            currentFilm.Year = film.Year!.Value;
            currentFilm.DirectorId = film.DirectorId!.Value;
            currentFilm.Plot = film.Plot;
            currentFilm.RatingId = film.RatingId!.Value;
            currentFilm.ReleaseDate = film.ReleaseDate!.Value;
            currentFilm.CountryOfOriginId = film.CountryOfOriginId!.Value;
            currentFilm.Genres = genres;
            await _filmRepository.SaveAsync();
        }

        return RedirectToAction("Index");
    }

    [HttpGet("delete/{filmId}")]
    public async Task<ActionResult> Delete(Guid filmId)
    {
        var film = await _filmRepository.GetAsync(filmId);
        if (film is null)
        {
            return RedirectToAction("Index");
        }

        return View(film);
    }

    [HttpPost("delete/{Id}")]
    public async Task<ActionResult> Delete(Domain.Entities.Film film)
    {
        var filmToDelete = await _filmRepository.GetAsync(film.Id);
        if (filmToDelete is null)
        {
            return RedirectToAction("Index");
        }

        _filmRepository.Delete(filmToDelete);
        await _filmRepository.SaveAsync();

        return RedirectToAction("Index");
    }
}

FilmLibrary.WebApp/Controllers/GenresController.cs
using FilmLibrary.Domain.Contracts.Repositories;
using FilmLibrary.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace FilmLibrary.WebApp.Controllers;

[Route("/genres")]
public class GenresController : Controller
{
    private readonly ILogger<GenresController> _logger;
    private readonly IGenreRepository _genreRepository;

    public GenresController(ILogger<GenresController> logger, IGenreRepository genreRepository)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _genreRepository = genreRepository ?? throw new ArgumentNullException(nameof(genreRepository));
    }

    public async Task<ActionResult> Index(string search, Pagination pagination)
    {
        if (string.IsNullOrEmpty(search))
        {
            var paginated = await _genreRepository.GetPaginatedAsync(pagination.Page, pagination.Count);
            return View(paginated);
        }
        else
        {
            var paginatedSearchResult = await _genreRepository.PaginatedSearchAsync(search, pagination.Page,
                pagination.Count);
            ViewBag.SearchString = search;
            return View(paginatedSearchResult);
        }
    }

    [HttpGet("add")]
    public ActionResult Add()
    {
        return View();
    }

    [HttpPost("add")]
    public async Task<ActionResult> Add(Genre genre)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }

        _genreRepository.Create(new Domain.Entities.Genre { Name = genre.Name });
        await _genreRepository.SaveAsync();

        return RedirectToAction("Index");
    }

    [HttpGet("details/{genreId}")]
    public async Task<ActionResult> Details(Guid genreId)
    {
        var genre = await _genreRepository.GetAsync(genreId);
        if (genre is null)
        {
            return RedirectToAction("Index");
        }

        return View(genre);
    }

    [HttpGet("edit/{genreId}")]
    public async Task<ActionResult> Edit(Guid genreId)
    {
        var genre = await _genreRepository.GetAsync(genreId);
        if (genre is null)
        {
            return RedirectToAction("Index");
        }

        return View(new Genre { Name = genre.Name });
    }

    [HttpPost("edit/{genreId}")]
    public async Task<ActionResult> Edit(Guid genreId, Genre genre)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }

        var currentGenre = await _genreRepository.GetAsync(genreId);
        if (currentGenre is not null)
        {
            currentGenre.Name = genre.Name;
            await _genreRepository.SaveAsync();
        }

        return RedirectToAction("Index");
    }

    [HttpGet("delete/{genreId}")]
    public async Task<ActionResult> Delete(Guid genreId)
    {
        var genre = await _genreRepository.GetAsync(genreId);
        if (genre is null)
        {
            return RedirectToAction("Index");
        }

        return View(genre);
    }

    [HttpPost("delete/{Id}")]
    public async Task<ActionResult> Delete(Domain.Entities.Genre genre)
    {
        var genreToDelete = await _genreRepository.GetAsync(genre.Id);
        if (genreToDelete is null)
        {
            return RedirectToAction("Index");
        }

        _genreRepository.Delete(genreToDelete);
        await _genreRepository.SaveAsync();

        return RedirectToAction("Index");
    }
}

FilmLibrary.WebApp/Views/Films/Add.cshtml
@model Film
@{ ViewData["Title"] = "Agregar película"; }

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Inicio</a></li>
        <li class="breadcrumb-item"><a asp-controller="Films" asp-action="Index">Películas</a></li>
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
</nav>

<h2>@ViewData["Title"]</h2>

<form method="post" class="row g-3">
    @Html.AntiForgeryToken()

    <div class="col-12 col-md-6">
        <label asp-for="Title" class="form-label">Título</label>
        <input type="text" asp-for="Title" class="form-control">
        <span class="text-danger" asp-validation-for="Title"></span>
    </div>

    <div class="col-12 col-md-2">
        <label asp-for="Year" class="form-label">Año</label>
        <input type="number" asp-for="Year" class="form-control">
        <span class="text-danger" asp-validation-for="Year"></span>
    </div>

    <div class="col-12 col-md-4">
        <label asp-for="DirectorId" class="form-label">Director</label>
        <select class="form-select" asp-for="DirectorId">
            <option value="">- seleccionar -</option>
            @foreach (var director in (ViewBag.Directors as IEnumerable<FilmLibrary.Domain.Entities.Director>)!)
            {
                <option value="@director.Id">@director.Name</option>
            }
        </select>
        <span class="text-danger" asp-validation-for="DirectorId"></span>
    </div>

    <div class="col-12">
        <label asp-for="Plot" class="form-label">Argumento</label>
        <textarea asp-for="Plot" class="form-control"></textarea>
        <span class="text-danger" asp-validation-for="Plot"></span>
    </div>

    <div class="col-12 col-md-2">
        <label asp-for="RatingId" class="form-label">Clasificación</label>
        <select class="form-select" asp-for="RatingId">
            <option value="">- seleccionar -</option>
            @foreach (var rating in (ViewBag.Ratings as IEnumerable<FilmLibrary.Domain.Entities.Rating>)!)
            {
                <option value="@rating.Id">@rating.Name</option>
            }
        </select>
        <span class="text-danger" asp-validation-for="RatingId"></span>
    </div>

    <div class="col-12 col-md-4">
        <label asp-for="ReleaseDate" class="form-label">Fecha de estreno</label>
        <input type="date" asp-for="ReleaseDate" class="form-control">
        <span class="text-danger" asp-validation-for="ReleaseDate"></span>
    </div>

    <div class="col-12 col-md-6">
        <label asp-for="CountryOfOriginId" class="form-label">País de origen</label>
        <select class="form-select" asp-for="CountryOfOriginId">
            <option value="">- seleccionar -</option>
            @foreach (var country in (ViewBag.Countries as IEnumerable<FilmLibrary.Domain.Entities.Country>)!)
            {
                <option value="@country.Id">@country.Name</option>
            }
        </select>
        <span class="text-danger" asp-validation-for="CountryOfOriginId"></span>
    </div>

    <div class="col-12">
        <label asp-for="GenreIds" class="form-label">Género(s)</label>
        <select asp-for="GenreIds" class="form-select" multiple>
            @foreach (var genre in (ViewBag.Genres as IEnumerable<FilmLibrary.Domain.Entities.Genre>)!)
            {
                <option value="@genre.Id">@genre.Name</option>
            }
        </select>
        <span class="text-danger" asp-validation-for="GenreIds"></span>
    </div>

    <div class="col-12 mt-3">
        <input type="submit" value="Agregar" class="btn btn-primary">
        <input type="reset" value="Restablecer" class="btn btn-secondary">
    </div>
</form>

<div class="mt-2">
    <a asp-action="Index" class="btn btn-info">Volver a la lista</a>
</div>

FilmLibrary.WebApp/Views/Films/Create.cshtml
@model Film
@{ ViewData["Title"] = "Crear película"; }

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Inicio</a></li>
        <li class="breadcrumb-item"><a asp-controller="Films" asp-action="Index">Películas</a></li>
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
</nav>

<h2>@ViewData["Title"]</h2>

<form method="post" class="row g-3">
    @Html.AntiForgeryToken()

    <div class="col-12 col-md-6">
        <label asp-for="Title" class="form-label">Título</label>
        <input type="text" asp-for="Title" class="form-control">
        <span class="text-danger" asp-validation-for="Title"></span>
    </div>

    <div class="col-12 col-md-2">
        <label asp-for="Year" class="form-label">Año</label>
        <input type="number" asp-for="Year" class="form-control">
        <span class="text-danger" asp-validation-for="Year"></span>
    </div>

    <div class="col-12 col-md-4">
        <label asp-for="DirectorId" class="form-label">Director</label>
        <select class="form-select" asp-for="DirectorId">
            @foreach (var director in (ViewBag.Directors as IEnumerable<FilmLibrary.Domain.Entities.Director>)!)
            {
                <option value="@director.Id">@director.Name</option>
            }
        </select>
        <span class="text-danger" asp-validation-for="DirectorId"></span>
    </div>

    <div class="col-12">
        <label asp-for="Plot" class="form-label">Argumento</label>
        <textarea asp-for="Plot" class="form-control"></textarea>
        <span class="text-danger" asp-validation-for="Plot"></span>
    </div>

    <div class="col-12 col-md-2">
        <label asp-for="RatingId" class="form-label">Clasificación</label>
        <select class="form-select" asp-for="RatingId">
            @foreach (var rating in (ViewBag.Ratings as IEnumerable<FilmLibrary.Domain.Entities.Rating>)!)
            {
                <option value="@rating.Id">@rating.Name</option>
            }
        </select>
        <span class="text-danger" asp-validation-for="RatingId"></span>
    </div>

    <div class="col-12 col-md-4">
        <label asp-for="ReleaseDate" class="form-label">Fecha de estreno</label>
        <input type="date" asp-for="ReleaseDate" class="form-control">
        <span class="text-danger" asp-validation-for="ReleaseDate"></span>
    </div>

    <div class="col-12 col-md-6">
        <label asp-for="CountryOfOriginId" class="form-label">País de origen</label>
        <select class="form-select" asp-for="CountryOfOriginId">
            @foreach (var country in (ViewBag.Countries as IEnumerable<FilmLibrary.Domain.Entities.Country>)!)
            {
                <option value="@country.Id">@country.Name</option>
            }
        </select>
        <span class="text-danger" asp-validation-for="CountryOfOriginId"></span>
    </div>

    <div class="col-12 mt-3">
        <input type="submit" value="Crear" class="btn btn-primary">
        <input type="reset" value="Restablecer" class="btn btn-secondary">
    </div>
</form>

<div class="mt-2">
    <a asp-action="Index" class="btn btn-info">Volver a la lista</a>
</div>

FilmLibrary.WebApp/Views/Films/Delete.cshtml
@model FilmLibrary.Domain.Entities.Film
@{ ViewData["Title"] = "Eliminar película"; }

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Inicio</a></li>
        <li class="breadcrumb-item"><a asp-controller="Films" asp-action="Index">Películas</a></li>
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
</nav>

<h2>@ViewData["Title"]</h2>

<div class="alert alert-danger">¿Está seguro que desea eliminar esta película?</div>

<div>
    <dl>
        <dt>Id</dt>
        <dd>@Model.Id</dd>
    </dl>
    <dl>
        <dt>Título</dt>
        <dd>@Model.Title</dd>
    </dl>
    <dl>
        <dt>Año</dt>
        <dd>@Model.Year</dd>
    </dl>
    <dl>
        <dt>Director</dt>
        <dd>@Model.Director?.Name</dd>
    </dl>
    <dl>
        <dt>Argumento</dt>
        <dd>@Model.Plot</dd>
    </dl>
    <dl>
        <dt>Clasificación</dt>
        <dd>@Model.Rating?.Name</dd>
    </dl>
    <dl>
        <dt>Fecha de estreno</dt>
        <dd>@Model.ReleaseDate.ToString("d")</dd>
    </dl>
    <dl>
        <dt>País de origen</dt>
        <dd>@Model.CountryOfOrigin?.Name</dd>
    </dl>
    <dl>
        <dt>Géneros</dt>
        <dd>
            <ul>
                @foreach (var genre in Model.Genres)
                {
                    <li>@genre.Name</li>
                }
            </ul>
        </dd>
    </dl>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div>
        <input type="submit" class="btn btn-danger" value="Eliminar">
    </div>
}

<div class="mt-2">
    <a asp-action="Index" class="btn btn-info">Volver a la lista</a>
</div>

FilmLibrary.WebApp/Views/Films/MissingData.cshtml
@{
    ViewData["Title"] = "Faltan datos";
}

<h2>@ViewData["Title"]</h2>

<p>Antes de poder agregar una película, debe agregar los directores, países y géneros que va a necesitar.</p>

<p>Datos faltantes:</p>
<ul>
    @if (ViewBag.Directors == true)
    {
        <li>Directores - <a asp-controller="Directors" asp-action="Add">agregar</a>.</li>
    }
    @if (ViewBag.Countries == true)
    {
        <li>Países - <a asp-controller="Countries" asp-action="Add">agregar</a>.</li>
    }
    @if (ViewBag.Genres == true)
    {
        <li>Géneros - <a asp-controller="Genres" asp-action="Add">agregar</a>.</li>
    }
</ul>

<a asp-action="Index" class="btn btn-info">Volver a la lista</a>